[package]
name = "geox"
version = "0.1.0"
edition = "2018"
description = "Shim to simplify using PostGIS types with sqlx"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
license = "Apache-2.0 OR MIT"

[dependencies]
geo = "0.17.1"
geozero = { version = "0.7.4", features = ["with-postgis-sqlx"] }
sqlx = "0.5.5"

[dev-dependencies.sqlx]
version = "0.5.5"
features = ["runtime-tokio-rustls", "postgres"]
