[package]
name = "geox"
version = "0.3.1"
edition = "2018"
description = "Shim to simplify using PostGIS types with sqlx and async-graphql"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
license = "Apache-2.0 OR MIT"
repository = "https://github.com/bbqsrc/geox"

[dependencies]
async-graphql = { version = "3", optional = true } 
geo = "0.17.1"
geozero = { version = "0.7.4", features = ["with-postgis-sqlx"], optional = true }
serde = { version = "1.0.130", features = ["derive"], optional = true }
sqlx = { version = "0.5.5", optional = true }

[dev-dependencies.sqlx]
version = "0.5.5"
features = ["runtime-tokio-rustls", "postgres"]

[features]
sqlx05 = ["sqlx", "geozero"]